#!/usr/bin/env bash

# データベースをクリアして再作成するスクリプト
# 使用方法: ./db/reset_db

set -e

echo "データベースをクリアしています..."
psql -h gbf_discord_bot_rs_devcontainer-db-1.orb.local -U postgres -d postgres -f drop.sql

echo "データベースを再作成しています..."
psql -h gbf_discord_bot_rs_devcontainer-db-1.orb.local -U postgres -d postgres -f init.sql

echo "データベースのリセットが完了しました。"
